services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: backend   # (можно оставить/убрать)
    tty: true
    ports:
      - "2341:2341"  # публикуем порт наружу
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_PROXY=${OPENAI_PROXY}
      # на macOS из контейнера на хост ходим так:
      - ANKI_CONNECT_URL=http://host.docker.internal:8765
    networks:
      - app-network

  frontend:
    restart: always
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # container_name: frontend
    ports:
      - "2342:80"  # Nginx обычно слушает 80 внутри
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge